Feature/views wizard
stadt-land-energie-projekt/sl-app pull request #122
Opened 2024-08-08 11:52 UTC by josihoppe

added new views and changed order of the old ones.
Also added the wizard from empowerplan, but made the buttons function (next/previous) with django + htmx

2024-08-08 11:54 UTC, josihoppe commented
I tried to get the wizard "active" look to work with hyperscript, but that didn't work. So that still needs to be done

2024-08-13 13:56 UTC, henhuy requested changes
Hey just looked at your wizard.
Thanks for implementing.
Sorry that I come up with this so late (i see that you put much effort into this), but IMO it would be better to not use HTMX for the wizard but instead use standard links.
There are two reasons:
1. in current solution the URL does not change as before. As we don't have a SPA here, I would do as much as possible in seperated views and urls. I think this is no big change.
2. This would also simplify your implementation of next and previous buttons (which is cool, but also comlicated) - to a simple href in the link, like this is implemented for some pages (see my comment)

Maybe we can talk about this changes soon.

2024-08-13 13:56 UTC, henhuy commented on slapp/templates/pages/map.html
> +          <button hx-post="{% url 'explorer:details' %}"
Here wizard href is hardcoded, which makes it easier IMO, instead of calling next_step url and dynamically load next view

2024-08-19 14:34 UTC, henhuy approved these changes

2024-08-19 14:41 UTC, merged